spring:
  profiles:
    active: dev
  application:
    name: zaggle-travel-module

app:
  message: This is primary Application Property for ${spring.application.name}

kafka:
      topic: zigDevTopic-2